name: Code Review

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pylint flake8 your-custom-linter

      - name: Run linters
        run: |
          pylint your_project/
          flake8 your_project/

      - name: Post results
        run: python scripts/post_comments.py
