name: Code Review

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.py' # Trigger on any Python file changes in the PR
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout PR
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: '3.x'
    - name: Install dependencies
      run: |
            pip install pylint
    #        pip install flake8==7.1.0
    # - name: Install Dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
    - name: Get list of changed files
      id: files
      run: |
        if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.py$' || true)
        else
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD | grep '\.py$' || true)
        fi
        echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

    - name: Run Pylint on changed files
      run: |
        pylint $CHANGED_FILES
